load("@aspect_rules_js//js:defs.bzl", "js_binary")

js_binary(
    name = "hello_world",
    entry_point = "hello_world.js",
)

js_binary(
    name = "es1",
    entry_point = "es1.js",
)

js_binary(
    name = "es2",
    entry_point = "es2.js",
)

js_binary(
    name = "es3",
    entry_point = "es3.js",
)
