load("@aspect_rules_js//js:defs.bzl", "js_binary")

js_binary(
    name = "es1",
    entry_point = "es1.mjs",
    data = ["//chpt11/utils"],
)

js_binary(
    name = "es2",
    entry_point = "es2.mjs",
    data = ["//chpt11/utils"],
)

js_binary(
    name = "es3",
    entry_point = "es3.mjs",
    data = ["//chpt11/utils"],
)

