load("@aspect_rules_js//js:defs.bzl", "js_binary")

js_binary(
    name = "lesson",
    entry_point = "lesson.js"
)

js_binary(
    name = "es",
    entry_point = "es.js",
)

# js_binary(
#     name = "es2",
#     entry_point = "es2.js",
# )

# js_binary(
#     name = "es3",
#     entry_point = "es3.js",
# )

# # js_binary(
#     name = "es4",
#     entry_point = "es4.js",
# )
